use_frameworks!
target 'DataStoreAdvanced_Example' do
    platform :osx, '10.9'
    platform :ios, '8.0'
    
    pod 'DataStoreAdvanced', :path => '../'
	pod 'FMDB'
        
    target 'DataStoreAdvanced_Tests' do
        platform :ios, '8.0'
		inherit! :search_paths
    end
end
