use_frameworks!
target 'DataStoreAdvanced_Example' do
    platform :ios, '8.0'
    
    pod 'DataStoreAdvanced', :path => '../'
	pod 'FMDB'
        
    target 'DataStoreAdvanced_Tests' do
		inherit! :search_paths
    end
end

target 'DataStoreAdvanced_Populate' do
	platform :osx, '10.9'
    pod 'DataStoreAdvanced', :path => '../'
	pod 'FMDB'
end